# Generated by Django 3.1.4 on 2020-12-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='DeaprtmentId',
            new_name='DepartmentId',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='dpartmentName',
            new_name='DepartmentName',
        ),
    ]
